[package]
edition = "2018"
name = "ra_vfs"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
walkdir = "2.2.7"
relative-path = "0.4.0"
rustc-hash = "1.0"
crossbeam-channel = "0.3.5"
log = "0.4.6"
# until https://github.com/passcod/notify/issues/169 is fixed
notify = { git = "https://github.com/vemoo/notify/", branch = "v4-legacy" }
drop_bomb = "0.1.0"

thread_worker = { path = "../thread_worker" }
ra_arena = { path = "../ra_arena" }

[dev-dependencies]
tempfile = "3"
flexi_logger = "0.10.0"
