[package]
edition = "2018"
name = "ra_vfs"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
walkdir = "2.2.7"
relative-path = "0.4.0"
rustc-hash = "1.0"
crossbeam-channel = "0.3.5"
log = "0.4.6"
notify = "4.0.9"
drop_bomb = "0.1.0"
parking_lot = "0.7.0"

thread_worker = { path = "../thread_worker" }

[dev-dependencies]
tempfile = "3"
flexi_logger = "0.10.0"
